// Function Set
$(document).ready(function(){$('.jenis-a').click(function(){$(".jenis").removeClass('jenis-active');$(".jenis[data-id='"+$(this).attr('data-id')+"']").addClass("jenis-active");$(".jenis-a").removeClass('active-a');$(this).parent().find(".jenis-a").addClass('active-a')})})
$('.wrap #macamsoal').addClass("jenis");
var jeso = $('.wrap').children('#macamsoal'),macam1 = jeso.eq(0),macam2 = jeso.eq(1),macam3 = jeso.eq(2),macam4 = jeso.eq(3);
macam1.attr("data-id", "jenis1");
macam2.attr("data-id", "jenis2");
macam3.attr("data-id", "jenis3");
macam4.attr("data-id", "jenis4");
// HTML
var kodemacamsoal = $("<div class='jenis-menu'><ul><li><a class='jenis-a' data-id='jenis1' id='tps1'>Penalaran Umum</a></li><li><a class='jenis-a' data-id='jenis2' id='tps2'>Pemahaman Bacaan dan Menulis</a></li><li><a class='jenis-a' data-id='jenis3' id='tps3'>Pengetahuan dan Pemahaman Umum</a></li><li><a class='jenis-a' data-id='jenis4' id='tps4'>Pengetahuan Kuantitatif</a></li></ul></div>");$(".wrap").prepend(kodemacamsoal);
var sopeum = $("<h2>Penalaran Umum</h2>").addClass('sopeum-list');$(".penalaranumum").prepend(sopeum);
var sopebu = $("<h2>Pemahaman Bacaan dan Menulis</h2>");$(".pemahamanbacaandanmenulis").prepend(sopebu);
var sopepu = $("<h2>Pengetahuan dan Pemahaman Umum</h2>");$(".pengetahuandanpemahamanumum").prepend(sopepu);
var sokuan = $("<h2>Pengetahuan Kuantitatif</h2>");$(".pengetahuankuantitatif").prepend(sokuan);
// Timer
var timer=$("<button id='kerjakan'>Mulai Kerjakan!</button><div id='kotakwaktu'><span id='waktutotal'/><span id='waktusubtest'/></div>");$(".wrap").before(timer);$(".jenis").each(function(){$(this).children('section').each(function(index){$(this).prepend("<span class='nomorsoal'>"+(index+1)+".</span>")})});$('#kerjakan').click(function(){function waktutotal(elementName,minutes,seconds){var element,endTime,hours,mins,msLeft,time;function twoDigits(n){return(n<=9?"0"+n:n)}function updateTimer(){msLeft=endTime-(+new Date);if(msLeft<1000){element.innerHTML="Waktu Habis!";$('#waktutotal').attr("style","padding: 20px;width:100% !important");$('#waktusubtest').attr("style","display:none");$('head').append("<style>#waktutotal:before{content:''!important;display:none}}</style>");$('.wrap').addClass('hide')}else{time=new Date(msLeft);hours=time.getUTCHours();mins=time.getUTCMinutes();element.innerHTML=(hours?hours+':'+twoDigits(mins):mins)+':'+twoDigits(time.getUTCSeconds());setTimeout(updateTimer,time.getUTCMilliseconds()+500)}}element=document.getElementById(elementName);endTime=(+new Date)+1000*(60*minutes+seconds)+500;updateTimer()}waktutotal("waktutotal",120,0);$('#kotakwaktu').attr("style","display: inline-block;text-align: center;color: white;background: #19abea;font-weight: 900;font-size: 150%;width: 100%;");$('#waktutotal').attr("style","padding: 20px;");$('head').append("<style>#waktutotal:before{content:'Sisa Waktu Total'}#waktusubtest:before, #waktutotal:before {font-size: 60%;display: block;font-weight: 100;}#main{padding:0 !important}</style>");$('#kerjakan, header, footer, .deskripsi').hide();$('.wrap').removeClass('hide')});$('a.jenis-a[data-id=jenis1]').click(function(){$('head').append("<style>#waktusubtest {background: #0d8bc1;padding: 20px;}#waktusubtest:before {content:'Sisa Waktu Subtest'}#kotakwaktu span{width:50%!important}</style>")});$('a.jenis-a[data-id=jenis2], a.jenis-a[data-id=jenis3], a.jenis-a[data-id=jenis4]').addClass('soalunavail')
// Submit Message
$("#ContactForm1_contact-form-submit").click(function(){if($('#ContactForm1_contact-form-success-message').is('.contact-form-success-message-with-border')){$('.wrap').html("<div class='selesai-atas'>TryOut selesai, terima kasih!</div><div class='selesai-bawah'>Kembali ke <a href='https://zida.kodejarwo.com'>ZIDA</a></div>").removeClass('hide');$('#kontak, #skorUTBK, #emc-score').addClass('hide')}})
